Parameters:
  extAccount:
    Type: String
    Description: AWS account id that can assume CrossAccountRole role
  environment:
    Type: String
    Description: Environment name

Resources:
  myBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Sub 'ets-${AWS::AccountId}-${environment}-s3-bucket'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      resource: Mystack/myBucket/Resource
      comment: Shared S3 bucket for the environment

  mySqs:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName:
        !Sub 'ets-${AWS::AccountId}-${environment}-queue'
      VisibilityTimeout: 300
    Metadata:
      resource: Mystack/mySqs/Resource
      comment: sqs where bucket should send notifications